### ISSUE TITLE
UnhandledError

### ISSUE THREAD

**Issue by inputsh** [RolfKoenders/ulauncher-myip#3]
How I triggered it:

* Changed the keyword from `glab` to `git`
* Changed the URL to the self-hosted instance.
* Entered my token (with `api` scope).

End result:

```
Message: 'com.github.brpaz.ulauncher-gitlab'
Error Name: UnhandledError
Type: KeyError

Stacktrace:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 198, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 417, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.brpaz.ulauncher-gitlab'

```

I've tried switching a field or two and I always seem to trigger this stacktrace. I've tried leaving the keyword to `glab`, as well as using GitLab.com access token instead of my own instance.

**Comment by inputsh** [comment]
Sorry, reported this to the wrong plugin since I was checking out multiple at once.
